

export const BASIC_DATA_SC = {
    //环节ID
    
    //调查取证
    caseDoc_SC_caseLinktypeId:'225104abe84023ce073b871367159e48',
    //移交移送
    transfei_SC_caseLinktypeId:'fbe7cb1a9b604cb0f3e42a48a2fdbed2',
    transfei_SC_huanjieAndDocId:'da38d8106dbbf881be4d99e719481c6c',
    //当事人权利
    partyRights_SC_caseLinktypeId:'775aee2b45c0b3ddc6ce945c15fba961',
    //决定执行
    penaltyExecution_SC_caseLinktypeId:'adb151c01264c1223220d14c937d920e',
    //强制执行
    forceExecute_SC_caseLinktypeId:'6ea9a839618b1783423278582e7228b5',
    //撤销立案
    cancelCase_SC_caseLinktypeId:'db8081cab22aa3316eafe51e1985887f',
    //行政强制措施
    adminCoerciveMeasure_SC_caseLinktypeId:'aa8e772d42a2ae77c4d26a03884f6f49',
    //不予处罚 环节id caseLinktypeId
    noPenalty_SC_caseLinktypeId:'e2149ddf5ee554764772da751a2fcbb6',





    
    //行政强制措施 环节id caseLinktypeId
    adminCoerciveMeasure_JX_caseLinktypeId:'c9493b367f429c2b55eea4bbb3627e36',
    //解除（延长）行政强制措施 环节id caseLinktypeId
    removeOrPrelong_JX_caseLinktypeId:'0521fdf305674d1a51759887431e48ff',
    //案件调查报告 环节id caseLinktypeId
    caseInvestig_JX_caseLinktypeId:'0eb11095af8afa6db6dd1662af989316',
    //案件调查报告 文书id
    caseInvestig_JX_huanjieAndDocId:'7a6bfb6e830342bc9fe3436a44b726e5',
    //违法行为通知书 环节id caseLinktypeId
    illegalActionForm_JX_caseLinktypeId:'211e903b962bc83a8360a6f625b13598',
    //违法行为通知书 文书id
    illegalActionForm_JX_huanjieAndDocId:'d82bb32374e4c6d02e1849d293316a4d',
    //责令改正违法行为通知书 环节id caseLinktypeId
    forceCorrect_JX_caseLinktypeId:'bb444320ed1e19585b18547772ab81d7',
    //责令改正违法行为通知书 文书id
    forceCorrect_JX_huanjieAndDocId:'f8370e3069fabd74791be14973b2ddfd',
    //移交移送 环节id
    transfei_JX_caseLinktypeId:'59031d79a5fdb79324769cd69216c1ef',
    //不予处罚 环节id caseLinktypeId
    noPenalty_JX_caseLinktypeId:'d17c1a83a26a76ec7fe64a0c2415b5a5',
    //当事人权利 环节id caseLinktypeId
    partyRights_JX_caseLinktypeId:'f1a074e649cff0387b59d9d76448d551',
    //重大案件讨论 环节id
    importCaseDiss_JX_caseLinktypeId:'1a05eb5d2202f8a69039c35569a7e9a7',
    //重大案件讨论 文书id
    importCaseDiss_JX_huanjieAndDocId:'35fb8de9cc995b1df22095bb7ec89754',
    //处罚决定 环节id caseLinktypeId
    punishDecisionDoc_JX_caseLinktypeId:'ab7312400b99fc39d681d1c8af78ff12',
    //强制执行 环节id
    forceExecute_JX_caseLinktypeId:'50db0706e4a5389ab0a32583d279335a',
    //处罚执行 环节id
    punishExecute_JX_caseLinktypeId:'b64b697a79aa90d5f9b9d84d3aaea48e',
    //申请法院强制执行 环节id
    courtPunishExecute_JX_caseLinktypeId:'1edc383bb4d438262ab2f687c4d15dfb',
    //申请法院强制执行 文书id
    courtPunishExecute_JX_huanjieAndDocId:'b3085802e1391ceb4629f20412261691',
    //结案报告 环节id caseLinktypeId
    finishCaseReport_JX_caseLinktypeId:'40cc145c41b6392db1080ce4fe2db1dd',
    //结案报告 docId
    finishCaseReport_JX_huanjieAndDocId:'63c5b014da18b4f64d5dd8a49bd0c3b9',
    

}