export const BASIC_DATA_JX = {
    //环节ID
    //立案登记 环节id caseLinktypeId
    establish_JX_caseLinktypeId:'3b203c7dcb3ab617ab6a61060253c7af',
    //立案登记 文书id
    establish_JX_huanjieAndDocId:'a4416d89a9e6884fe9ae0b1f43f0f885',
    //调查报告
    caseDoc_JX_caseLinktypeId:'0e36b3ec81cff5d675eec9687c339de2',
    //行政强制措施 环节id caseLinktypeId
    adminCoerciveMeasure_JX_caseLinktypeId:'c9493b367f429c2b55eea4bbb3627e36',
    //案件调查报告 环节id caseLinktypeId
    caseInvestig_JX_caseLinktypeId:'0eb11095af8afa6db6dd1662af989316',
    //案件调查报告 文书id
    caseInvestig_JX_huanjieAndDocId:'7a6bfb6e830342bc9fe3436a44b726e5',
    //违法行为通知书 环节id caseLinktypeId
    illegalActionForm_JX_caseLinktypeId:'211e903b962bc83a8360a6f625b13598',
    //违法行为通知书 文书id
    illegalActionForm_JX_huanjieAndDocId:'d82bb32374e4c6d02e1849d293316a4d',
    //责令改正违法行为通知书 环节id caseLinktypeId
    forceCorrect_JX_caseLinktypeId:'bb444320ed1e19585b18547772ab81d7',
    //责令改正违法行为通知书 文书id
    forceCorrect_JX_huanjieAndDocId:'f8370e3069fabd74791be14973b2ddfd',
    //移交移送 环节id
    transfei_JX_caseLinktypeId:'59031d79a5fdb79324769cd69216c1ef',
    //不予处罚 环节id caseLinktypeId
    noPenalty_JX_caseLinktypeId:'d17c1a83a26a76ec7fe64a0c2415b5a5',
    //当事人权利 环节id caseLinktypeId
    partyRights_JX_caseLinktypeId:'f1a074e649cff0387b59d9d76448d551',
    //重大案件讨论 环节id
    importCaseDiss_JX_caseLinktypeId:'1a05eb5d2202f8a69039c35569a7e9a7',
    //重大案件讨论 文书id
    importCaseDiss_JX_huanjieAndDocId:'35fb8de9cc995b1df22095bb7ec89754',
    //处罚决定 环节id caseLinktypeId
    punishDecisionDoc_JX_caseLinktypeId:'ab7312400b99fc39d681d1c8af78ff12',
    //强制执行 环节id
    forceExecute_JX_caseLinktypeId:'50db0706e4a5389ab0a32583d279335a',
    //处罚执行 环节id
    punishExecute_JX_caseLinktypeId:'b64b697a79aa90d5f9b9d84d3aaea48e',
    //申请法院强制执行 环节id
    courtPunishExecute_JX_caseLinktypeId:'1edc383bb4d438262ab2f687c4d15dfb',
    //申请法院强制执行 文书id
    courtPunishExecute_JX_huanjieAndDocId:'b3085802e1391ceb4629f20412261691',
    //结案报告 环节id caseLinktypeId
    finishCaseReport_JX_caseLinktypeId:'40cc145c41b6392db1080ce4fe2db1dd',
    //结案报告 docId
    finishCaseReport_JX_huanjieAndDocId:'63c5b014da18b4f64d5dd8a49bd0c3b9',



    //文书ID
}