export const BASIC_DATA_JX = {
    //环节ID
    //立案登记 环节id caseLinktypeId
    establish_JX_caseLinktypeId:'3b203c7dcb3ab617ab6a61060253c7af',
    //立案登记 文书id
    establish_JX_huanjieAndDocId:'a4416d89a9e6884fe9ae0b1f43f0f885',
    //案件调查
    caseDoc_JX_caseLinktypeId:'0e36b3ec81cff5d675eec9687c339de2',
    //行政强制措施 环节id caseLinktypeId
    adminCoerciveMeasure_JX_caseLinktypeId:'c9493b367f429c2b55eea4bbb3627e36',
    //案件调查报告 环节id caseLinktypeId
    caseInvestig_JX_caseLinktypeId:'0eb11095af8afa6db6dd1662af989316',
    //案件调查报告 文书id
    caseInvestig_JX_huanjieAndDocId:'7a6bfb6e830342bc9fe3436a44b726e5',
    //违法行为通知书 环节id caseLinktypeId
    illegalActionForm_JX_caseLinktypeId:'211e903b962bc83a8360a6f625b13598',
    //违法行为通知书 文书id
    illegalActionForm_JX_huanjieAndDocId:'d82bb32374e4c6d02e1849d293316a4d',
    //责令改正违法行为通知书 环节id caseLinktypeId
    forceCorrect_JX_caseLinktypeId:'bb444320ed1e19585b18547772ab81d7',
    //责令改正违法行为通知书 文书id
    forceCorrect_JX_huanjieAndDocId:'f8370e3069fabd74791be14973b2ddfd',
    //移交移送 环节id
    transfei_JX_caseLinktypeId:'59031d79a5fdb79324769cd69216c1ef',
    //不予处罚 环节id caseLinktypeId
    noPenalty_JX_caseLinktypeId:'d17c1a83a26a76ec7fe64a0c2415b5a5',
    //当事人权利 环节id caseLinktypeId
    partyRights_JX_caseLinktypeId:'f1a074e649cff0387b59d9d76448d551',
    //重大案件讨论 环节id
    importCaseDiss_JX_caseLinktypeId:'1a05eb5d2202f8a69039c35569a7e9a7',
    //重大案件讨论 文书id
    importCaseDiss_JX_huanjieAndDocId:'35fb8de9cc995b1df22095bb7ec89754',
    //处罚决定 环节id caseLinktypeId
    punishDecisionDoc_JX_caseLinktypeId:'ab7312400b99fc39d681d1c8af78ff12',
    //强制执行 环节id
    forceExecute_JX_caseLinktypeId:'50db0706e4a5389ab0a32583d279335a',
    //处罚执行 环节id
    punishExecute_JX_caseLinktypeId:'b64b697a79aa90d5f9b9d84d3aaea48e',
    //申请法院强制执行 环节id
    courtPunishExecute_JX_caseLinktypeId:'1edc383bb4d438262ab2f687c4d15dfb',
    //申请法院强制执行 文书id
    courtPunishExecute_JX_huanjieAndDocId:'b3085802e1391ceb4629f20412261691',
    //结案报告 环节id caseLinktypeId
    finishCaseReport_JX_caseLinktypeId:'40cc145c41b6392db1080ce4fe2db1dd',
    //结案报告 docId
    finishCaseReport_JX_huanjieAndDocId:'63c5b014da18b4f64d5dd8a49bd0c3b9',



    //文书ID
    //协助调查函 文书ID
    assistInvestigation_caseDocTypeId: '22aafe04d99115ab5ebf6e89f83a6039',
    //勘验笔录 文书ID
    inquestNotes_JX_caseDocTypeId: '442a43837c4b0ab911d9acfe8e62cfff',
    //现场笔录 文书ID
    sceneNotes_JX_caseDocTypeId: "123504045dcdf44a1e55d83ad02d2743",
    //行政强制措施现场笔录 文书ID
    adminCoerciveMeasureNote_JX_caseDocTypeId: "dad89e4f961b2793458cba01798730c5",
    //检查记录 文书ID
    inspectionRecord_caseDocTypeId: '192d1e329bda8641080a09d66ba4fcc5',
    //询问笔录 文书ID
    otherModle_JX_caseDocTypeId: 'fdfa1fe362f29bde2e09e04931977e3e',
    //视听资料（电子数据）证据记录单  文书ID
    audioEvidenceRecord_JX_caseDocTypeId: 'fff567fbb50b92dc81f3d2dbcbb3a8b0',
    //抽样取样凭证 文书ID
    obtaineEvidenceForm_JX_caseDocTypeId: '14b7ba9abdb393dcb105133fd2484238',
    //证据登记保存清单 
    evidenceListDoc_JX_caseDocTypeId: '6daeece3812c081f2fe62033b3070ce8',
    //行政强制执行决定书 
    enforceDecideDoc_JX_caseDocTypeId: '04f82dfb31400c5a6e7a113cdbf57406',
    //行政强制执行协议书
    adminEnforceAgreeDoc_JX_caseDocTypeId: '2de4881a940bf5f285344280db60b3c4',
    //中止（终结、恢复）行政强制执行审批表
    abortEndRecoverApprovalForm_JX_caseDocTypeId: '000102285dfa7847667b92fb41975002',
    //代履行决定书
    enforceInsteadDoc_JX_caseDocTypeId: '0f1dd1a4dc5702eec1363fe2e1a35fd2',
    //执法文书送达地址确认书
    deliveryConfirmDoc_JX_caseDocTypeId: '3be17698c76447727f7e7d627bf4b8f5',
    //当场行政处罚决定书
    spotAdmPunishDecisionDoc_JX_caseDocTypeId: '6668f1814b0b6074dc8eca7dd980a428',
    //证据登记保存审批表
    evidenceRegApprovalForm_JX_caseDocTypeId: '7e1078a4fc730bccbe639dfbd1825416',
    //分期（延期）缴纳罚款审批表
    stageDelayApprovalForm_JX_caseDocTypeId: '7ba8d7736240e28b4a211f072dc9dc05',
    //解除证据登记保存决定书
    deleteEvidence_JX_caseDocTypeId: 'f3dcf6bc6c99ecd79e6c157492f6a8db',
    //行政强制措施审批表
    adminCoerciveMeasureApproval_JX_caseDocTypeId: '4a69969a0ab457ac61511855b1e931ec',
    //行政强制措施决定书
    adminCoerciveMeasure_JX_caseDocTypeId: 'effe85a776b4531cd7e8436975750ecc',
    //延长行政强制措施审批表
    prolongAdminCoerciveMeasureApproval_JX_caseDocTypeId: '7911ddfed9610b44ec1bc56587ad87e7',
    //延长行政强制措施期限通知书
    prolongAdminCompulsoryDoc_JX_caseDocTypeId: '3358acf7a04923b636ed65ce3e5527ed',
    //行政强制措施解除审批表
    removeAdminCoerciveMeasureApproval_JX_caseDocTypeId: '68371556dd5ec522c711867a36a76a45',
    //解除行政强制措施决定书
    removeAdminCoerciveMeasureDoc_JX_caseDocTypeId: '4e10617c963ced86c6e818c23b69138f',
    //重大行政执法决定法制审核表
    majorAdminLawEnforceAudit_JX_caseDocTypeId: '46dd8bf75af2c9e6bb5d086b102d1b16',
    //重大案件讨论记录
    importantCaseTeamDissDoc_JX_caseDocTypeId: '1d6da633abd8cb3d69c5a45a9cf74c02',
    //听证通知书
    ea5f82857581c8e1bba04b6f1fa2e5b6_JX_caseDocTypeId: 'ea5f82857581c8e1bba04b6f1fa2e5b6',
    //听证笔录
    hearingRecordeDoc_JX_caseDocTypeId: '655bd5bbe641d957d8e2cf4865089a96',
    //听证报告书
    hearingReportDoc_JX_caseDocTypeId: 'dd1e5248c427896adfbc3afa13a131af',
    //分期（延期）缴纳罚款通知书
    payStageDoc_JX_caseDocTypeId: '7f3b7fe2851728670c52d6df312794cf',
    //行政处罚审批表
    adminPenaltyApprovalForm_JX_caseDocTypeId: 'c1a2732c52719153062c6e1441168cbe',
    //行政处罚决定书
    punishDecisionDoc_JX_caseDocTypeId: 'fb4eab5077beb790906145a529cbaf40',
    //催告书
    remindLetterDoc_JX_caseDocTypeId: '2928fcc7e6eeff2b43450a0f92cf6120',
    //行政强制执行审批表
    enforceDecideApprovalForm_JX_caseDocTypeId: '2f97d16fdc7dfe9b90fbf7979d7d17c8',
    //中止（终结、恢复）行政强制执行通知书
    enforceDoc_JX_caseDocTypeId: '925a6259030a77ef355d066923a4de0c',
    //执行公告
    executAnnounceDoc_JX_caseDocTypeId: '728d436c6ae3ecf1e1e1d5a0697f90b3',
    //送达回证
    deliverReceiptForm_JX_caseDocTypeId: '12a61541477a2cede003d93e50c1e762',
    //案件移送函
    caseTransLetter_JX_caseDocTypeId: '3d0b62c322df49bc69ed8bd9fee83ad0',
    //案件移送告知书
    caseTransNoticeDoc_JX_caseDocTypeId: '34bd2eeaf625f5cab254b0af5a9eccc3',
    //解除证据登记保存审批表
    removeEvidenceRegApprovalForm_JX_caseDocTypeId: 'e68821f21875c7dda472b378b3eaee31',
}